replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/cassandra
  tag: "4.1.3"

jvm:
  maxHeapSize: 2G
  newHeapSize: 512M

resources:
  limits:
    cpu: 4
    memory: "3Gi"
  requests:
    cpu: 2
    memory: "1Gi"

extraEnvVars:
  - name: MAX_HEAP_SIZE
    value: "2G"
  - name: HEAP_NEWSIZE
    value: "512M"
