replicaCount: 1
grafana:
  resources:
    limits:
      cpu: "400m"
      memory: "400Mi"
    requests:
      cpu: "200m"
      memory: "200Mi"

prometheus:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

alertmanager:
  enabled: false
#  resources:
#    limits:
#      cpu: "300m"
#      memory: "256Mi"
#    requests:
#      cpu: "150m"
#      memory: "128Mi"