# Image configuration
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: "16.2.0"  # Latest stable version
  pullPolicy: IfNotPresent

# Authentication
auth:
  enablePostgresUser: true
  postgresPassword: "postgres"
  username: "app"
  password: "app"
  database: "app"

# Primary configuration
primary:
  resources:
    limits:
      memory: "512Mi"  # Reduced from default
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

  # PostgreSQL configuration
  configuration: |
    shared_buffers = 128MB
    temp_buffers = 8MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    effective_cache_size = 256MB
    max_connections = 50
    random_page_cost = 1.1
    effective_io_concurrency = 200
    max_worker_processes = 4
    max_parallel_workers_per_gather = 2
    max_parallel_workers = 4
    max_parallel_maintenance_workers = 2
    autovacuum_max_workers = 2
    max_wal_size = 1GB
    min_wal_size = 80MB
    checkpoint_completion_target = 0.9
    default_statistics_target = 100

  # Pod security context
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true

  # Persistence configuration
  persistence:
    enabled: true
    size: "1Gi"
    storageClass: "hostpath"  # Docker Desktop default

  # Service configuration
  service:
    type: ClusterIP
    port: 5432

  # Health check probes
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
    
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

# Metrics configuration
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
  resources:
    limits:
      memory: "64Mi"
      cpu: "100m"
    requests:
      memory: "32Mi"
      cpu: "50m"

# High Availability (disabled for local dev)
replication:
  enabled: false
  synchronousCommit: "off"
  numSynchronousReplicas: 0
  applicationName: "my_application"

# Network policy
networkPolicy:
  enabled: false

# Extra configurations
extraEnvVars:
  - name: POSTGRES_EXTRA_FLAGS
    value: "-c shared_preload_libraries=pg_stat_statements"

# Disable TLS for local development
tls:
  enabled: false
  autoGenerated: false

# Volume permissions
volumePermissions:
  enabled: true

# Startup probe (helps with slow systems)
startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1